[package]
name = "sqpack_blue"
version = "0.0.9"
authors = ["CerulanLumina <CerulanLumina@users.noreply.github.com>"]

[features]
default = []
profile = []

[lib]
doctest = false

[dependencies]
byteorder = "1.2.7"
flate2 = "1.0.4"
indexmap = "1.0.2"

[dev-dependencies]
md5 = "0.6.0"
